### ISSUE TITLE
Differentiate library blocks and increase padding between library blocks? 

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/library_hours_rails#349]
We've received feedback from a library branch manager asking if the padding between library blocks can be increased. This is particularly noticeable when we have long library names (e.g. Marine Biology Library (Harold A. Miller) at Hopkins Marine Station, and SLAC National Accelerator Lab Research Library)

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/14897546/158676812-14a41084-7ecf-41f2-9626-6b364b39d4da.png">

Looking at it more closely, I find it hard to determine which rows belong to which library label. There are lines between the library blocks and rows, but the row lines aren't applied to the library label column. So my eye has a hard time successfully following the row. Increasing padding might help this, but I wonder if we need something more prominent to help the user's eye follow the library block. (Are zebra stripes out of style?) Perhaps @ggeisler has a quick opinion.

**Comment by ggeisler** [comment]
@saseestone I agree the spacing is tight and makes distinguishing rows more difficult than it should be.

I don't think zebra stripes is an ideal solution here, just because some of the rows are pretty tall and having different shaded strips that are tall or vary in height a lot can be visually messy.

Here are a couple of quick ideas to consider:


## Increase row margins
Adding `margin-bottom: 2rem;` to the `row`:

<img width="1192" alt="Screen Shot 2022-03-16 at 1 37 36 PM" src="https://user-images.githubusercontent.com/101482/158687344-d0346235-185f-4c99-aebe-58fdda3997fe.png">

## Increase row margins plus add a row border
The example above is better, but still seems harder to distinguish rows than ideal. Below I reduced the margin a bit to `margin-bottom: 1rem;` but added a `border-bottom: 1px dotted #a26624;` (same color as the library heading text) to the `row` to try to visually separate the rows with more than just whitespace:

<img width="1192" alt="Screen Shot 2022-03-16 at 1 38 58 PM" src="https://user-images.githubusercontent.com/101482/158687717-e4a18029-e4ad-49ee-bb5b-d7ec75571849.png">

## Increase row margins plus add a row border in lighter gray
Same as above but using a lighter color (`#bbb` for illustration purposes but we could use a light gray from the app color palette if we end up going with this) to try to mitigate the busyness of the horizontal lines we get by adding the row border:

<img width="1192" alt="Screen Shot 2022-03-16 at 1 40 13 PM" src="https://user-images.githubusercontent.com/101482/158688055-f092bc65-12ec-42a3-b211-0c36bf2f4333.png">

## Increase row margins (2rem) plus add a row border in lighter gray
This is basically both ideas combined. `margin-bottom: 2rem;` and `border-bottom: 1px dotted #bbb;`:

<img width="1192" alt="Screen Shot 2022-03-16 at 1 47 41 PM" src="https://user-images.githubusercontent.com/101482/158688344-358153bb-97c5-49df-80c0-4b8d33e8f43b.png">

**Comment by saseestone** [comment]
@ggeisler I do like the split extra whitespace (top and bottom of the row), and really like the addition of the row border.  I would defer to you about the color of the row border.  Do we need to think about contrast here?

I also noticed the library label moves to above the location and date row when the window is resized small. Does the border solution complicate the resizing of the window?

**Comment by ggeisler** [comment]
> Does the border solution complicate the resizing of the window?

I don't think so. Here's a mobile view:

<img width="566" alt="Screen Shot 2022-03-16 at 3 10 06 PM" src="https://user-images.githubusercontent.com/101482/158700073-78d4e946-ccb5-4466-8ea8-fe5686b9072b.png">

What do you think?

---

> Do we need to think about contrast here?

Again, I don't think so, because we aren't relying on the border for the separation; it's more an addition to the extra whitespace that is our primary way of visually separating the rows. So if you can't see the row border at all, it still works okay I think:

<img width="566" alt="Screen Shot 2022-03-16 at 3 10 33 PM" src="https://user-images.githubusercontent.com/101482/158699992-99fa51fd-70ee-4719-aa6b-12197e67fc43.png">

---

And at desktop size:

<img width="1185" alt="Screen Shot 2022-03-16 at 3 16 42 PM" src="https://user-images.githubusercontent.com/101482/158700546-0f84a967-895d-4c6c-a041-d1533d302695.png">

Admittedly, it isn't as clear a separation if you can't see the row separator, but maybe okay? We could go somewhat darker, I'm just worried that the darker we go the more you notice all the horizontal lines on the page and it makes it more distracting to focus on the actual content of the page. But we could go with whatever gray we have in the application color palette that is the next shade darker than `#bbb` perhaps.

**Comment by ggeisler** [comment]
Comparing the two mobile examples I posted above, I think it actually might work better on mobile without the row separator rule (but keeping the additional top and bottom padding). If you agree we could just add the row border at desktop breakpoints (when we know the library title will be next to, instead of above, its hours).

**Comment by saseestone** [comment]
I hear your goal to reduce the visual distraction of a dark line. I think going with #bbb is fine. And thanks for doing a quick mock in mobile view with the row separator in place.  Looks fine to me.

I think we have a winner! (i.e. Add padding to both top and bottom of row, plus dotted row border using #bbb)
